### PR TITLE
List directories first and sort case insensitive

### PR DESCRIPTION
**Pull request by fin-ger**
I added more sorting options for the directory listing.

Replaces #2

### CODE REVIEW

**Comment by jpillora** [comment]
I'd be happy to just do this (dirs first, ignore case sort) by default

**Comment by fin-ger** [comment]
So would there be `--disable-...` flags or would the behavior not be configurable?

**Comment by fin-ger** [comment]
Rebased and changed configuration -> ready to merge

**Comment by jpillora** [comment]
Awesome :) Thanks (yeah not configurable is fine)

**Comment by jpillora** [comment]
Released https://github.com/jpillora/serve/releases/tag/1.8.1 👍

**Pull request merged**
